#include <stdexcept>

int main() {
    try {
        // execute code that will add the two Sales_items
        // if the addition fails, the code throws a runtime_error exception
    }
    catch (std::runtime_error err) {

    }
	return 0;
}